{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "# Check these before running\n",
    "\n",
    "# KPUM Workstation\n",
    "studydir = '/mnt/e/Research/Projects/KPUM_NODDI/Data'\n",
    "niftibasefolder = 'nifti' # nifti basefolder to go within studydir\n",
    "codedir = os.path.join('/home/radio/KPUM_NODDI','code/kpum_noddi')\n",
    "datadirbasefolder = 'derivatives/dMRI_OrigProtocol'\n",
    "protocol = 'ORIG' # 'NEW'\n",
    "datadirbasefolder = 'derivatives/dMRI_np'\n",
    "protocol = 'NEW' # 'NEW'\n",
    "dPar = 1.7e-3\n",
    "\n",
    "\n",
    "# Finn's Laptop\n",
    "studydir = '/mnt/s/Research/Projects/KPUM_NODDI/Data'\n",
    "niftibasefolder = 'nifti' # nifti basefolder to go within studydir\n",
    "codedir = os.path.join(studydir,'code/kpum_noddi')\n",
    "codedir = os.path.join('/home/finn','Code/kpum_noddi')\n",
    "datadirbasefolder = 'derivatives/dMRI_np'\n",
    "protocol = 'NEW' # 'NEW'\n",
    "datadirbasefolder = 'derivatives/dMRI_Testing7_dmri_pipeline'\n",
    "protocol = 'NEW' # 'NEW'\n",
    "dPar = 1.4e-3 # value to use in NODDI estimation\n",
    "\n",
    "# tsv-files to keep track of in studydir/niftibasefolder\n",
    "subjecttrackerpath = os.path.join(studydir, datadirbasefolder)\n",
    "subjecttrackerfile = 'Subject_Tracker_for_dmri_pipeline.tsv'\n",
    "\n",
    "###################################################################################\n",
    "# USER INPUT\n",
    "\n",
    "# Participant details\n",
    "subject = '035'\n",
    "session = 'MR1'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "# Define I/O folders and files\n",
    "niftifolder = os.path.join(studydir, niftibasefolder, os.path.join(f'sub-{subject}',f'ses-{session}'))\n",
    "derivatives = os.path.join(studydir,datadirbasefolder)\n",
    "datadir = os.path.join(derivatives, os.path.join(f'sub-{subject}',f'ses-{session}'))\n",
    "if not os.path.exists(datadir): # then make this directory\n",
    "    os.makedirs(datadir)\n",
    "subjecttrackertsv = os.path.join(subjecttrackerpath, subjecttrackerfile)\n",
    "\n",
    "def perform_process(processcall) :\n",
    "    import os, subprocess\n",
    "    # Perform the process given by the processcall by launching into terminal\n",
    "    p=subprocess.Popen(processcall, stdout=subprocess.PIPE, shell=True)\n",
    "    # Poll process.stdout to show stdout live\n",
    "    while True:\n",
    "        output = p.stdout.readline()\n",
    "        if p.poll() is not None:\n",
    "            break\n",
    "        if output:\n",
    "            print(output.strip().decode(\"utf-8\"))\n",
    "    rc = p.poll()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "dwifslpreproc: Changing to scratch directory (/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwifslpreproc/dwifslpreproc-tmp-DKIHON/)\n",
      "dwifslpreproc: No slice encoding direction information present; assuming third axis corresponds to slices\n",
      "Command:  mrinfo dwi.mif -export_grad_mrtrix grad.b\n",
      "Command:  dwi2mask dwi.mif - | maskfilter - dilate - | mrconvert - eddy_mask.nii -datatype float32 -strides -1,+2,+3\n",
      "Command:  mrconvert dwi.mif eddy_in.nii -strides -1,+2,+3,+4 -export_grad_fsl bvecs bvals -export_pe_eddy eddy_config.txt eddy_indices.txt\n",
      "Command:  eddy_cuda10.2 --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --slm=linear --repol --mporder=8 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 --mbs_niter=20 --mbs_ksp=10 --mbs_lambda=10 --slspec=slspec.txt --out=dwi_post_eddy --verbose\n",
      "dwifslpreproc: CUDA version of 'eddy' was not successful; attempting OpenMP version\n",
      "Command:  eddy_cpu --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --slm=linear --repol --mporder=8 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 --mbs_niter=20 --mbs_ksp=10 --mbs_lambda=10 --slspec=slspec.txt --out=dwi_post_eddy --verbose\n",
      "dwifslpreproc: CUDA version of 'eddy' was not successful; attempting OpenMP version\n",
      "Command:  eddy_cpu --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --slm=linear --repol --mporder=8 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 --mbs_niter=20 --mbs_ksp=10 --mbs_lambda=10 --slspec=slspec.txt --out=dwi_post_eddy --verbose\n",
      "\n",
      "dwifslpreproc: [ERROR] eddy* --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --slm=linear --repol --mporder=8 --s2v_niter=10 --s2v_interp=trilinear --s2v_lambda=1 --mbs_niter=20 --mbs_ksp=10 --mbs_lambda=10 --slspec=slspec.txt --out=dwi_post_eddy --verbose (app.py:199)\n",
      "dwifslpreproc: [ERROR] Information from failed command:\n",
      "dwifslpreproc:\n",
      "               =============\n",
      "               eddy_cuda10.2\n",
      "               =============\n",
      "               Reading images\n",
      "               Performing volume-to-volume registration\n",
      "               Running Register\n",
      "               \n",
      "               ...................Allocated GPU # 0...................\n",
      "               Loading prediction maker\n",
      "               Evaluating prediction maker model\n",
      "               Checking for outliers\n",
      "               Calculating parameter updates\n",
      "               Iter: 0, Total mss = 2.90994\n",
      "               Loading prediction maker\n",
      "               Evaluating prediction maker model\n",
      "               Checking for outliers\n",
      "               Loading prediction maker\n",
      "               Evaluating prediction maker model\n",
      "               Calculating parameter updates\n",
      "               Iter: 1, Total mss = 3.24456\n",
      "               Loading prediction maker\n",
      "               Evaluating prediction maker model\n",
      "               Checking for outliers\n",
      "               Loading prediction maker\n",
      "               Evaluating prediction maker model\n",
      "               Calculating parameter updates\n",
      "               Iter: 2, Total mss = 3.33012\n",
      "               Loading prediction maker\n",
      "               Evaluating prediction maker model\n",
      "               Checking for outliers\n",
      "               \n",
      "               \n",
      "               ========\n",
      "               eddy_cpu\n",
      "               ========\n",
      "               Reading images\n",
      "               Performing volume-to-volume registration\n",
      "               Running Register\n",
      "               \n",
      "               \n",
      "               =============\n",
      "               eddy_cuda10.2\n",
      "               =============\n",
      "               Terminated\n",
      "               \n",
      "               \n",
      "               ========\n",
      "               eddy_cpu\n",
      "               ========\n",
      "               Terminated\n",
      "               \n",
      "               \n",
      "dwifslpreproc:\n",
      "dwifslpreproc: [ERROR] For debugging, inspect contents of scratch directory: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwifslpreproc\n",
      "dwifslpreproc: Scratch directory retained; location: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwifslpreproc\n",
      "cp: target 'eddy/.' is not a directory\n",
      "mv: cannot stat 'dwifslpreproc/field_*': No such file or directory\n",
      "mv: cannot stat 'dwifslpreproc/topup_*': No such file or directory\n",
      "mrmath: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] failed to open key/value file \"dwi_den_unr_eddy.mif\": No such file or directory\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] error opening image \"dwi_den_unr_eddy.mif\"\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] no filename supplied to standard input (broken pipe?)\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] error opening image \"-\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] cannot stat file \"meanb0tmp_brain_mask.nii\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] cannot stat file \"meanb0tmp_brain_mask.nii\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"meanb0tmp_brain_mask.nii\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"meanb0tmp_brain_mask.nii\"\u001b[0m\n",
      "dwibiascorrect: \n",
      "dwibiascorrect: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.\n",
      "dwibiascorrect: \n",
      "dwibiascorrect: Generated scratch directory: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-L6MD3T/\n",
      "Command:  mrconvert /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-L6MD3T/in.mif\n",
      "\n",
      "dwibiascorrect: [ERROR] mrconvert /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-L6MD3T/in.mif (dwibiascorrect:50)\n",
      "dwibiascorrect: [ERROR] Information from failed command:\n",
      "dwibiascorrect:\n",
      "                mrconvert: [ERROR] failed to open key/value file \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif\": No such file or directory\n",
      "                mrconvert: [ERROR] error opening image \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif\"\n",
      "dwibiascorrect:\n",
      "dwibiascorrect: [ERROR] For debugging, inspect contents of scratch directory: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-L6MD3T/\n",
      "dwibiascorrect: Scratch directory retained; location: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-L6MD3T/\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"preproc/dwi_den_unr_eddy_N4.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"preproc/dwi_den_unr_eddy_N4.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"preproc/mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"preproc/mask.mif\"\u001b[0m\n",
      "Command:  dwiextract /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif -output median\n",
      "\n",
      "dwinormalise: [ERROR] dwiextract /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif -output median (individual.py:66)\n",
      "dwinormalise: [ERROR] Information from failed command:\n",
      "dwinormalise:\n",
      "              dwiextract: [ERROR] failed to open key/value file \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif\": No such file or directory\n",
      "              dwiextract: [ERROR] error opening image \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif\"\n",
      "              mrmath: [ERROR] no filename supplied to standard input (broken pipe?)\n",
      "              mrmath: [ERROR] error opening image \"-\"\n",
      "              mrstats: [ERROR] no filename supplied to standard input (broken pipe?)\n",
      "              mrstats: [ERROR] error opening image \"-\"\n",
      "dwinormalise:\n",
      "mrinfo: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrinfo: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] failed to open key/value file \"../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] error opening image \"../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "dwi2tensor: \u001b[01;31m[ERROR] no filename supplied to standard input (broken pipe?)\u001b[0m\n",
      "dwi2tensor: \u001b[01;31m[ERROR] error opening image \"-\"\u001b[0m\n",
      "tensor2metric: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\": No such file or directory\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\": No such file or directory\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\"\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\": No such file or directory\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\": No such file or directory\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] Could not interpret string \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\" as either an image path or a numerical value\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] As image: \u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] As numerical value: \u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] error converting string \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\" to complex float (no valid conversion)\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/bin/dipy_fit_dki\", line 7, in <module>\n",
      "    run_flow(ReconstDkiFlow())\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/flow_runner.py\", line 89, in run_flow\n",
      "    return flow.run(**args)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/reconst.py\", line 821, in run\n",
      "    io_it = self.get_io_iterator()\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/workflow.py\", line 37, in get_io_iterator\n",
      "    io_it = io_iterator_(frame, self.run,\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 202, in io_iterator_\n",
      "    return io_iterator(inputs, out_dir, outputs, output_strategy, mix_names,\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 146, in io_iterator\n",
      "    io_it.set_inputs(*inputs)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 222, in set_inputs\n",
      "    self.file_existence_check(args)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 283, in file_existence_check\n",
      "    raise IOError('File not found: ' + path)\n",
      "OSError: File not found: ../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.nii\n",
      "mrmath: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\": No such file or directory\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\": No such file or directory\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\"\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\"\u001b[0m\n",
      "\n",
      "dwifslpreproc: [ERROR] Unhandled Python exception:\n",
      "dwifslpreproc: [ERROR]   FileNotFoundError: [Errno 2] No such file or directory: 'eddy_openmp_failure_output.txt'\n",
      "dwifslpreproc: [ERROR] Traceback:\n",
      "dwifslpreproc: [ERROR]   /home/finn/Software/mrtrix3/bin/dwifslpreproc:939 (in execute())\n",
      "dwifslpreproc: [ERROR]     with open('eddy_openmp_failure_output.txt', 'wb') as eddy_output_file:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/finn/Software/mrtrix3/bin/dwifslpreproc\", line 1328, in <module>\n",
      "    mrtrix3.execute() #pylint: disable=no-member\n",
      "  File \"/home/finn/Software/mrtrix3/lib/mrtrix3/__init__.py\", line 94, in execute\n",
      "    app._execute(inspect.getmodule(inspect.stack()[1][0])) # pylint: disable=protected-access\n",
      "  File \"/home/finn/Software/mrtrix3/lib/mrtrix3/app.py\", line 254, in _execute\n",
      "    if os.getcwd() != WORKING_DIR:\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "cp: target 'eddy/.' is not a directory\n",
      "mv: cannot stat 'dwifslpreproc/field_*': No such file or directory\n",
      "mv: cannot stat 'dwifslpreproc/topup_*': No such file or directory\n",
      "mrmath: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] failed to open key/value file \"dwi_den_unr_eddy.mif\": No such file or directory\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] error opening image \"dwi_den_unr_eddy.mif\"\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] no filename supplied to standard input (broken pipe?)\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] error opening image \"-\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] cannot stat file \"meanb0tmp_brain_mask.nii\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] cannot stat file \"meanb0tmp_brain_mask.nii\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"meanb0tmp_brain_mask.nii\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"meanb0tmp_brain_mask.nii\"\u001b[0m\n",
      "dwibiascorrect: \n",
      "dwibiascorrect: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.\n",
      "dwibiascorrect: \n",
      "dwibiascorrect: Generated scratch directory: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-24T2GE/\n",
      "Command:  mrconvert /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-24T2GE/in.mif\n",
      "\n",
      "dwibiascorrect: [ERROR] mrconvert /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-24T2GE/in.mif (dwibiascorrect:50)\n",
      "dwibiascorrect: [ERROR] Information from failed command:\n",
      "dwibiascorrect:\n",
      "                mrconvert: [ERROR] failed to open key/value file \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif\": No such file or directory\n",
      "                mrconvert: [ERROR] error opening image \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif\"\n",
      "dwibiascorrect:\n",
      "dwibiascorrect: [ERROR] For debugging, inspect contents of scratch directory: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-24T2GE/\n",
      "dwibiascorrect: Scratch directory retained; location: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-24T2GE/\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"preproc/dwi_den_unr_eddy_N4.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"preproc/dwi_den_unr_eddy_N4.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"preproc/mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"preproc/mask.mif\"\u001b[0m\n",
      "Command:  dwiextract /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif -output median\n",
      "\n",
      "dwinormalise: [ERROR] dwiextract /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif -output median (individual.py:66)\n",
      "dwinormalise: [ERROR] Information from failed command:\n",
      "dwinormalise:\n",
      "              dwiextract: [ERROR] failed to open key/value file \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif\": No such file or directory\n",
      "              dwiextract: [ERROR] error opening image \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif\"\n",
      "              mrmath: [ERROR] no filename supplied to standard input (broken pipe?)\n",
      "              mrmath: [ERROR] error opening image \"-\"\n",
      "              mrstats: [ERROR] no filename supplied to standard input (broken pipe?)\n",
      "              mrstats: [ERROR] error opening image \"-\"\n",
      "dwinormalise:\n",
      "mrinfo: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrinfo: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] failed to open key/value file \"../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] error opening image \"../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "dwi2tensor: \u001b[01;31m[ERROR] no filename supplied to standard input (broken pipe?)\u001b[0m\n",
      "dwi2tensor: \u001b[01;31m[ERROR] error opening image \"-\"\u001b[0m\n",
      "tensor2metric: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\": No such file or directory\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\": No such file or directory\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\"\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\": No such file or directory\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\": No such file or directory\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] Could not interpret string \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\" as either an image path or a numerical value\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] As image: \u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] As numerical value: \u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] error converting string \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\" to complex float (no valid conversion)\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/bin/dipy_fit_dki\", line 7, in <module>\n",
      "    run_flow(ReconstDkiFlow())\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/flow_runner.py\", line 89, in run_flow\n",
      "    return flow.run(**args)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/reconst.py\", line 821, in run\n",
      "    io_it = self.get_io_iterator()\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/workflow.py\", line 37, in get_io_iterator\n",
      "    io_it = io_iterator_(frame, self.run,\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 202, in io_iterator_\n",
      "    return io_iterator(inputs, out_dir, outputs, output_strategy, mix_names,\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 146, in io_iterator\n",
      "    io_it.set_inputs(*inputs)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 222, in set_inputs\n",
      "    self.file_existence_check(args)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 283, in file_existence_check\n",
      "    raise IOError('File not found: ' + path)\n",
      "OSError: File not found: ../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.nii\n",
      "mrmath: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\": No such file or directory\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\": No such file or directory\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\"\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "/home/finn/Code/kpum_noddi/shell/dmri_noddi.sh: line 148: cd: derivatives/dMRI/sub-035/ses-MR1/dwi/AMICO/NODDI: No such file or directory\n",
      "mv: cannot stat '*.nii.gz': No such file or directory\n",
      "gzip: sub-035_ses-MR1_dir-AP_desc-preproc-inorm_recon-NODDI-dPar-0p0017_*.nii.gz: No such file or directory\n",
      "mv: cannot stat 'AMICO/NODDI/*': No such file or directory\n",
      "\n",
      "dwifslpreproc: [ERROR] Unhandled Python exception:\n",
      "dwifslpreproc: [ERROR]   FileNotFoundError: [Errno 2] No such file or directory: 'eddy_cuda_failure_output.txt'\n",
      "dwifslpreproc: [ERROR] Traceback:\n",
      "dwifslpreproc: [ERROR]   /home/finn/Software/mrtrix3/bin/dwifslpreproc:933 (in execute())\n",
      "dwifslpreproc: [ERROR]     with open('eddy_cuda_failure_output.txt', 'wb') as eddy_output_file:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/finn/Software/mrtrix3/bin/dwifslpreproc\", line 1328, in <module>\n",
      "    mrtrix3.execute() #pylint: disable=no-member\n",
      "  File \"/home/finn/Software/mrtrix3/lib/mrtrix3/__init__.py\", line 94, in execute\n",
      "    app._execute(inspect.getmodule(inspect.stack()[1][0])) # pylint: disable=protected-access\n",
      "  File \"/home/finn/Software/mrtrix3/lib/mrtrix3/app.py\", line 254, in _execute\n",
      "    if os.getcwd() != WORKING_DIR:\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "cp: target 'eddy/.' is not a directory\n",
      "mv: cannot stat 'dwifslpreproc/field_*': No such file or directory\n",
      "mv: cannot stat 'dwifslpreproc/topup_*': No such file or directory\n",
      "mrmath: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] failed to open key/value file \"dwi_den_unr_eddy.mif\": No such file or directory\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] error opening image \"dwi_den_unr_eddy.mif\"\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] no filename supplied to standard input (broken pipe?)\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] error opening image \"-\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] cannot stat file \"meanb0tmp_brain_mask.nii\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] cannot stat file \"meanb0tmp_brain_mask.nii\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"meanb0tmp_brain_mask.nii\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"meanb0tmp_brain_mask.nii\"\u001b[0m\n",
      "dwibiascorrect: \n",
      "dwibiascorrect: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.\n",
      "dwibiascorrect: \n",
      "dwibiascorrect: Generated scratch directory: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-7TTQBL/\n",
      "Command:  mrconvert /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-7TTQBL/in.mif\n",
      "\n",
      "dwibiascorrect: [ERROR] mrconvert /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-7TTQBL/in.mif (dwibiascorrect:50)\n",
      "dwibiascorrect: [ERROR] Information from failed command:\n",
      "dwibiascorrect:\n",
      "                mrconvert: [ERROR] failed to open key/value file \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif\": No such file or directory\n",
      "                mrconvert: [ERROR] error opening image \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif\"\n",
      "dwibiascorrect:\n",
      "dwibiascorrect: [ERROR] For debugging, inspect contents of scratch directory: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-7TTQBL/\n",
      "dwibiascorrect: Scratch directory retained; location: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-7TTQBL/\n",
      "/home/finn/Code/kpum_noddi/shell/dmri_noddi.sh: line 148: cd: derivatives/dMRI/sub-035/ses-MR1/dwi/AMICO/NODDI: No such file or directory\n",
      "mv: cannot stat '*.nii.gz': No such file or directory\n",
      "gzip: sub-035_ses-MR1_dir-AP_desc-preproc-inorm_recon-NODDI-dPar-0p0017_*.nii.gz: No such file or directory\n",
      "mv: cannot stat 'AMICO/NODDI/*': No such file or directory\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"preproc/dwi_den_unr_eddy_N4.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"preproc/dwi_den_unr_eddy_N4.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"preproc/mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"preproc/mask.mif\"\u001b[0m\n",
      "Command:  dwiextract /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif -output median\n",
      "\n",
      "dwinormalise: [ERROR] dwiextract /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif -output median (individual.py:66)\n",
      "dwinormalise: [ERROR] Information from failed command:\n",
      "dwinormalise:\n",
      "              dwiextract: [ERROR] failed to open key/value file \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif\": No such file or directory\n",
      "              dwiextract: [ERROR] error opening image \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif\"\n",
      "              mrmath: [ERROR] no filename supplied to standard input (broken pipe?)\n",
      "              mrmath: [ERROR] error opening image \"-\"\n",
      "              mrstats: [ERROR] no filename supplied to standard input (broken pipe?)\n",
      "              mrstats: [ERROR] error opening image \"-\"\n",
      "dwinormalise:\n",
      "mrinfo: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrinfo: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] failed to open key/value file \"../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] error opening image \"../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "dwi2tensor: \u001b[01;31m[ERROR] no filename supplied to standard input (broken pipe?)\u001b[0m\n",
      "dwi2tensor: \u001b[01;31m[ERROR] error opening image \"-\"\u001b[0m\n",
      "tensor2metric: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\": No such file or directory\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\": No such file or directory\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\"\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\": No such file or directory\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\": No such file or directory\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] Could not interpret string \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\" as either an image path or a numerical value\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] As image: \u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] As numerical value: \u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] error converting string \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\" to complex float (no valid conversion)\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/bin/dipy_fit_dki\", line 7, in <module>\n",
      "    run_flow(ReconstDkiFlow())\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/flow_runner.py\", line 89, in run_flow\n",
      "    return flow.run(**args)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/reconst.py\", line 821, in run\n",
      "    io_it = self.get_io_iterator()\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/workflow.py\", line 37, in get_io_iterator\n",
      "    io_it = io_iterator_(frame, self.run,\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 202, in io_iterator_\n",
      "    return io_iterator(inputs, out_dir, outputs, output_strategy, mix_names,\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 146, in io_iterator\n",
      "    io_it.set_inputs(*inputs)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 222, in set_inputs\n",
      "    self.file_existence_check(args)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 283, in file_existence_check\n",
      "    raise IOError('File not found: ' + path)\n",
      "OSError: File not found: ../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.nii\n",
      "mrmath: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\": No such file or directory\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\": No such file or directory\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\"\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "/home/finn/Code/kpum_noddi/shell/dmri_noddi.sh: line 148: cd: derivatives/dMRI/sub-035/ses-MR1/dwi/AMICO/NODDI: No such file or directory\n",
      "mv: cannot stat '*.nii.gz': No such file or directory\n",
      "gzip: sub-035_ses-MR1_dir-AP_desc-preproc-inorm_recon-NODDI-dPar-0p0017_*.nii.gz: No such file or directory\n",
      "mv: cannot stat 'AMICO/NODDI/*': No such file or directory\n",
      "\n",
      "dwifslpreproc: [ERROR] Unhandled Python exception:\n",
      "dwifslpreproc: [ERROR]   FileNotFoundError: [Errno 2] No such file or directory: 'eddy_cuda_failure_output.txt'\n",
      "dwifslpreproc: [ERROR] Traceback:\n",
      "dwifslpreproc: [ERROR]   /home/finn/Software/mrtrix3/bin/dwifslpreproc:933 (in execute())\n",
      "dwifslpreproc: [ERROR]     with open('eddy_cuda_failure_output.txt', 'wb') as eddy_output_file:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/finn/Software/mrtrix3/bin/dwifslpreproc\", line 1328, in <module>\n",
      "    mrtrix3.execute() #pylint: disable=no-member\n",
      "  File \"/home/finn/Software/mrtrix3/lib/mrtrix3/__init__.py\", line 94, in execute\n",
      "    app._execute(inspect.getmodule(inspect.stack()[1][0])) # pylint: disable=protected-access\n",
      "  File \"/home/finn/Software/mrtrix3/lib/mrtrix3/app.py\", line 254, in _execute\n",
      "    if os.getcwd() != WORKING_DIR:\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "cp: target 'eddy/.' is not a directory\n",
      "mv: cannot stat 'dwifslpreproc/field_*': No such file or directory\n",
      "mv: cannot stat 'dwifslpreproc/topup_*': No such file or directory\n",
      "mrmath: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] failed to open key/value file \"dwi_den_unr_eddy.mif\": No such file or directory\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] error opening image \"dwi_den_unr_eddy.mif\"\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] no filename supplied to standard input (broken pipe?)\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] error opening image \"-\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] cannot stat file \"meanb0tmp_brain_mask.nii\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] cannot stat file \"meanb0tmp_brain_mask.nii\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"meanb0tmp_brain_mask.nii\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"meanb0tmp_brain_mask.nii\"\u001b[0m\n",
      "dwibiascorrect: \n",
      "dwibiascorrect: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.\n",
      "dwibiascorrect: \n",
      "dwibiascorrect: Generated scratch directory: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-B6AF5Q/\n",
      "Command:  mrconvert /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-B6AF5Q/in.mif\n",
      "\n",
      "dwibiascorrect: [ERROR] mrconvert /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-B6AF5Q/in.mif (dwibiascorrect:50)\n",
      "dwibiascorrect: [ERROR] Information from failed command:\n",
      "dwibiascorrect:\n",
      "                mrconvert: [ERROR] failed to open key/value file \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif\": No such file or directory\n",
      "                mrconvert: [ERROR] error opening image \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif\"\n",
      "dwibiascorrect:\n",
      "dwibiascorrect: [ERROR] For debugging, inspect contents of scratch directory: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-B6AF5Q/\n",
      "dwibiascorrect: Scratch directory retained; location: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-B6AF5Q/\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"preproc/dwi_den_unr_eddy_N4.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"preproc/dwi_den_unr_eddy_N4.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"preproc/mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"preproc/mask.mif\"\u001b[0m\n",
      "Command:  dwiextract /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif -output median\n",
      "\n",
      "dwinormalise: [ERROR] dwiextract /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif -output median (individual.py:66)\n",
      "dwinormalise: [ERROR] Information from failed command:\n",
      "dwinormalise:\n",
      "              dwiextract: [ERROR] failed to open key/value file \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif\": No such file or directory\n",
      "              dwiextract: [ERROR] error opening image \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif\"\n",
      "              mrmath: [ERROR] no filename supplied to standard input (broken pipe?)\n",
      "              mrmath: [ERROR] error opening image \"-\"\n",
      "              mrstats: [ERROR] no filename supplied to standard input (broken pipe?)\n",
      "              mrstats: [ERROR] error opening image \"-\"\n",
      "dwinormalise:\n",
      "mrinfo: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrinfo: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] failed to open key/value file \"../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] error opening image \"../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "dwi2tensor: \u001b[01;31m[ERROR] no filename supplied to standard input (broken pipe?)\u001b[0m\n",
      "dwi2tensor: \u001b[01;31m[ERROR] error opening image \"-\"\u001b[0m\n",
      "tensor2metric: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\": No such file or directory\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\": No such file or directory\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\"\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\": No such file or directory\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\": No such file or directory\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] Could not interpret string \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\" as either an image path or a numerical value\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] As image: \u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] As numerical value: \u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] error converting string \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\" to complex float (no valid conversion)\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/bin/dipy_fit_dki\", line 7, in <module>\n",
      "    run_flow(ReconstDkiFlow())\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/flow_runner.py\", line 89, in run_flow\n",
      "    return flow.run(**args)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/reconst.py\", line 821, in run\n",
      "    io_it = self.get_io_iterator()\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/workflow.py\", line 37, in get_io_iterator\n",
      "    io_it = io_iterator_(frame, self.run,\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 202, in io_iterator_\n",
      "    return io_iterator(inputs, out_dir, outputs, output_strategy, mix_names,\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 146, in io_iterator\n",
      "    io_it.set_inputs(*inputs)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 222, in set_inputs\n",
      "    self.file_existence_check(args)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 283, in file_existence_check\n",
      "    raise IOError('File not found: ' + path)\n",
      "OSError: File not found: ../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.nii\n",
      "mrmath: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\": No such file or directory\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\": No such file or directory\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\"\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "/home/finn/Code/kpum_noddi/shell/dmri_noddi.sh: line 148: cd: derivatives/dMRI/sub-035/ses-MR1/dwi/AMICO/NODDI: No such file or directory\n",
      "mv: cannot stat '*.nii.gz': No such file or directory\n",
      "gzip: sub-035_ses-MR1_dir-AP_desc-preproc-inorm_recon-NODDI-dPar-0p0017_*.nii.gz: No such file or directory\n",
      "mv: cannot stat 'AMICO/NODDI/*': No such file or directory\n",
      "\n",
      "dwifslpreproc: [ERROR] Unhandled Python exception:\n",
      "dwifslpreproc: [ERROR]   FileNotFoundError: [Errno 2] No such file or directory: 'eddy_cuda_failure_output.txt'\n",
      "dwifslpreproc: [ERROR] Traceback:\n",
      "dwifslpreproc: [ERROR]   /home/finn/Software/mrtrix3/bin/dwifslpreproc:933 (in execute())\n",
      "dwifslpreproc: [ERROR]     with open('eddy_cuda_failure_output.txt', 'wb') as eddy_output_file:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/finn/Software/mrtrix3/bin/dwifslpreproc\", line 1328, in <module>\n",
      "    mrtrix3.execute() #pylint: disable=no-member\n",
      "  File \"/home/finn/Software/mrtrix3/lib/mrtrix3/__init__.py\", line 94, in execute\n",
      "    app._execute(inspect.getmodule(inspect.stack()[1][0])) # pylint: disable=protected-access\n",
      "  File \"/home/finn/Software/mrtrix3/lib/mrtrix3/app.py\", line 254, in _execute\n",
      "    if os.getcwd() != WORKING_DIR:\n",
      "FileNotFoundError: [Errno 2] No such file or directory\n",
      "cp: target 'eddy/.' is not a directory\n",
      "mv: cannot stat 'dwifslpreproc/field_*': No such file or directory\n",
      "mv: cannot stat 'dwifslpreproc/topup_*': No such file or directory\n",
      "mrmath: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] failed to open key/value file \"dwi_den_unr_eddy.mif\": No such file or directory\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] error opening image \"dwi_den_unr_eddy.mif\"\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] no filename supplied to standard input (broken pipe?)\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] error opening image \"-\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] cannot stat file \"meanb0tmp_brain_mask.nii\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] cannot stat file \"meanb0tmp_brain_mask.nii\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"meanb0tmp_brain_mask.nii\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"meanb0tmp_brain_mask.nii\"\u001b[0m\n",
      "dwibiascorrect: \n",
      "dwibiascorrect: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.\n",
      "dwibiascorrect: \n",
      "dwibiascorrect: Generated scratch directory: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-CPKZOD/\n",
      "Command:  mrconvert /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-CPKZOD/in.mif\n",
      "\n",
      "dwibiascorrect: [ERROR] mrconvert /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-CPKZOD/in.mif (dwibiascorrect:50)\n",
      "dwibiascorrect: [ERROR] Information from failed command:\n",
      "dwibiascorrect:\n",
      "                mrconvert: [ERROR] failed to open key/value file \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif\": No such file or directory\n",
      "                mrconvert: [ERROR] error opening image \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwi_den_unr_eddy.mif\"\n",
      "dwibiascorrect:\n",
      "dwibiascorrect: [ERROR] For debugging, inspect contents of scratch directory: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-CPKZOD/\n",
      "dwibiascorrect: Scratch directory retained; location: /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/preproc/dwibiascorrect-tmp-CPKZOD/\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"preproc/dwi_den_unr_eddy_N4.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"preproc/dwi_den_unr_eddy_N4.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"preproc/mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"preproc/mask.mif\"\u001b[0m\n",
      "Command:  dwiextract /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif -output median\n",
      "\n",
      "dwinormalise: [ERROR] dwiextract /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif -bzero - | mrmath - mean - -axis 3 | mrstats - -mask /mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif -output median (individual.py:66)\n",
      "dwinormalise: [ERROR] Information from failed command:\n",
      "dwinormalise:\n",
      "              dwiextract: [ERROR] failed to open key/value file \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif\": No such file or directory\n",
      "              dwiextract: [ERROR] error opening image \"/mnt/s/Research/Projects/KPUM_NODDI/Data/derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_dir-AP_desc-preproc_dwi.mif\"\n",
      "              mrmath: [ERROR] no filename supplied to standard input (broken pipe?)\n",
      "              mrmath: [ERROR] error opening image \"-\"\n",
      "              mrstats: [ERROR] no filename supplied to standard input (broken pipe?)\n",
      "              mrstats: [ERROR] error opening image \"-\"\n",
      "dwinormalise:\n",
      "mrinfo: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrinfo: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"derivatives/dMRI/sub-035/ses-MR1/dwi/sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] failed to open key/value file \"../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "dwiextract: \u001b[01;31m[ERROR] error opening image \"../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "dwi2tensor: \u001b[01;31m[ERROR] no filename supplied to standard input (broken pipe?)\u001b[0m\n",
      "dwi2tensor: \u001b[01;31m[ERROR] error opening image \"-\"\u001b[0m\n",
      "tensor2metric: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\": No such file or directory\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\": No such file or directory\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\"\u001b[0m\n",
      "tensor2metric: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_DT.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\": No such file or directory\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\": No such file or directory\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] Could not interpret string \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\" as either an image path or a numerical value\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] As image: \u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\"\u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] As numerical value: \u001b[0m\n",
      "mrcalc: \u001b[01;31m[ERROR] error converting string \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_MD.nii\" to complex float (no valid conversion)\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/bin/dipy_fit_dki\", line 7, in <module>\n",
      "    run_flow(ReconstDkiFlow())\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/flow_runner.py\", line 89, in run_flow\n",
      "    return flow.run(**args)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/reconst.py\", line 821, in run\n",
      "    io_it = self.get_io_iterator()\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/workflow.py\", line 37, in get_io_iterator\n",
      "    io_it = io_iterator_(frame, self.run,\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 202, in io_iterator_\n",
      "    return io_iterator(inputs, out_dir, outputs, output_strategy, mix_names,\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 146, in io_iterator\n",
      "    io_it.set_inputs(*inputs)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 222, in set_inputs\n",
      "    self.file_existence_check(args)\n",
      "  File \"/home/finn/Software/miniconda3/envs/kpum_wsl/lib/python3.10/site-packages/dipy/workflows/multi_io.py\", line 283, in file_existence_check\n",
      "    raise IOError('File not found: ' + path)\n",
      "OSError: File not found: ../sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.nii\n",
      "mrmath: \u001b[00;31m[WARNING] existing output files will be overwritten\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\": No such file or directory\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] cannot stat file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\": No such file or directory\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] unknown format for image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\"\u001b[0m\n",
      "mrmath: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi_eval.nii\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] unknown format for image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"No_image\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_dir-AP_desc-preproc-inorm_dwi.mif\"\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] failed to open key/value file \"sub-035_ses-MR1_space-dwi_mask.mif\": No such file or directory\u001b[0m\n",
      "mrconvert: \u001b[01;31m[ERROR] error opening image \"sub-035_ses-MR1_space-dwi_mask.mif\"\u001b[0m\n",
      "/home/finn/Code/kpum_noddi/shell/dmri_noddi.sh: line 148: cd: derivatives/dMRI/sub-035/ses-MR1/dwi/AMICO/NODDI: No such file or directory\n",
      "mv: cannot stat '*.nii.gz': No such file or directory\n",
      "gzip: sub-035_ses-MR1_dir-AP_desc-preproc-inorm_recon-NODDI-dPar-0p0017_*.nii.gz: No such file or directory\n",
      "mv: cannot stat 'AMICO/NODDI/*': No such file or directory\n"
     ]
    }
   ],
   "source": [
    "########################################\n",
    "## START\n",
    "\n",
    "import os \n",
    "import pandas as pd\n",
    "\n",
    "currdir = os.getcwd()\n",
    "os.chdir(studydir)\n",
    "\n",
    "## Process to perform - dmri_pipeline\n",
    "process = 'dmri_pipeline'\n",
    "processfile = 'dmri_pipeline.sh'\n",
    "processfilepath = os.path.join(codedir,'shell', processfile)\n",
    "processcall = f\"bash {processfilepath} {subject} {session} {studydir} -d {derivatives} -dPar {dPar} -p {protocol}\"\n",
    "perform_process(processcall)\n",
    "\n",
    "os.chdir(currdir)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "kpum_wsl",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
